// All permission keys used by the backend's authorize() middleware.
// A user has a permission if it is in their role's defaults OR in their
// customPermissions list. Super Admin and Admin skip permission checks
// entirely (see middleware/permissionMiddleware.js).

const PERMISSIONS = {
  // Sales & Billing
  SALES_CREATE: "sales.create",
  SALES_VIEW: "sales.view",
  SALES_EDIT: "sales.edit",
  SALES_DELETE: "sales.delete",
  SALES_CANCEL: "sales.cancel",

  // Invoices & Quotations
  INVOICE_CREATE: "invoice.create",
  INVOICE_VIEW: "invoice.view",
  INVOICE_EDIT: "invoice.edit",
  INVOICE_DELETE: "invoice.delete",
  INVOICE_CANCEL: "invoice.cancel",
  QUOTATION_MANAGE: "quotation.manage",

  // Products & Inventory
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_EDIT: "products.edit",
  PRODUCTS_DELETE: "products.delete",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",

  // Customers & Suppliers
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_EDIT: "customers.edit",
  CUSTOMERS_DELETE: "customers.delete",
  SUPPLIERS_MANAGE: "suppliers.manage",

  // Purchases
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_VIEW: "purchases.view",
  PURCHASES_EDIT: "purchases.edit",
  PURCHASES_DELETE: "purchases.delete",

  // Reports
  REPORTS_SALES: "reports.sales",
  REPORTS_PURCHASES: "reports.purchases",
  REPORTS_GST: "reports.gst",
  REPORTS_FINANCIAL: "reports.financial",
  REPORTS_INVENTORY: "reports.inventory",

  // Employee Management
  EMPLOYEES_CREATE: "employees.create",
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_EDIT: "employees.edit",
  EMPLOYEES_DELETE: "employees.delete",

  // Attendance Management
  ATTENDANCE_CREATE: "attendance.create",
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_EDIT: "attendance.edit",
  ATTENDANCE_DELETE: "attendance.delete",
  ATTENDANCE_REPORTS: "attendance.reports",

  // Administration & Settings
  USERS_MANAGE: "users.manage",
  SETTINGS_MANAGE: "settings.manage",
  AUDIT_VIEW: "audit.view",
};

// Default permissions mapped to standard roles
const ROLE_PERMISSIONS = {
  "Super Admin": Object.values(PERMISSIONS),

  "Admin": Object.values(PERMISSIONS),

  "Manager": [
    PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_EDIT, PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_EDIT, PERMISSIONS.INVOICE_CANCEL,
    PERMISSIONS.QUOTATION_MANAGE,
    PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.PURCHASES_CREATE, PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.REPORTS_SALES, PERMISSIONS.REPORTS_PURCHASES, PERMISSIONS.REPORTS_INVENTORY,
    PERMISSIONS.EMPLOYEES_CREATE, PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.EMPLOYEES_EDIT,
    PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_EDIT, PERMISSIONS.ATTENDANCE_REPORTS,
  ],

  "Cashier": [
    PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_VIEW,
    PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_VIEW,
  ],

  "Inventory Staff": [
    PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.PURCHASES_CREATE, PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.REPORTS_INVENTORY,
    PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_VIEW,
  ],

  "Accountant": [
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.REPORTS_SALES, PERMISSIONS.REPORTS_PURCHASES, PERMISSIONS.REPORTS_GST, PERMISSIONS.REPORTS_FINANCIAL,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_REPORTS,
  ],

  "Viewer": [
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
